### ISSUE TITLE
update user last login time at server 

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-android#182]

**Comment by Zulqarnain-Mustafa** [comment]
@ijunaidfarooq please devise an appropriate way to update last login from applications.

**Comment by ijunaidfarooq** [comment]
@Zulqarnain-Mustafa according to past discussions and What I think is best is to just create an endpoint for it for being used on Android and iOS. That will be very appropriate for both apps.

e.g

`PATCH /v1/users/last-login?preauth`

and a change in `POST /v1/users` so that when the user is being created we will add its last login from media side for the first time.

Will it be a biggie from apps to call this endpoint?

**Comment by marcoherbst** [comment]
How is it done in Dashboard?

**Comment by ijunaidfarooq** [comment]
Dashboard can connect directly to db. Apps cant. 

https://github.com/evercam/evercam-dashboard/blob/master/app/helpers/sessions_helper.rb#L2-L7

**Comment by marcoherbst** [comment]
This conversation is veering away from what I think is sensible, but it raises 2 other questions:

1. Make a list of places where Dash talks to DB directly
https://github.com/evercam/evercam-dashboard/issues/1475

2. Consider how to do user activity logging
https://github.com/evercam/evercam-media/issues/224

I'll close this issue.
