### ISSUE TITLE
Search engine presence work ...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-android#203]
1. Have a look in Google WebMaster Tools
2. Consider Deep Linking / Public Cameras

**Comment by marcoherbst** [comment]
![image](https://cloud.githubusercontent.com/assets/5648894/18788736/f09b0f6a-819f-11e6-9272-aa7086366d65.png)

**Comment by marcoherbst** [comment]
@Zulqarnain-Mustafa spend an hour looking at this and thinking about.  Do the obvious stuff & ask me for anything non-obvious.

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst I do not think that we need deep linking for now, because our application structure is not like that, when we search Evercam, it show all the websites and mobile applications in list, and when searching on mobile device , it shows application downloading icon and when user tap on it it move to AppStore for downloading on iPhone.

**Comment by marcoherbst** [comment]
That's fine for now.

What I had in mind, actually, was:

User searches for "Traffic Camera, Dublin" and they would get a link to:

https://Google-Play-Evercam-App-Deep-URL to install app & show Traffic Cameras.

This is a task for another day.
