### ISSUE TITLE
Don't save H264 url in camera object if vendor / model specified.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-android#211]

**Comment by marcoherbst** [comment]
This is written "don't save" ... but I guess you know that obviously it is not just about not saving it, it's about making the user interface in such a way as that it is obvious that one specifies EITHER the Vend/Mod OR manually inputs the URLs. If you're not sure, let's discuss.

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst as I discussed with @azharmalik3 we are sending following parameters from android when we create camera:
{id='', 
name='', 
isPublic=false,
 isOnline=true, 
vendor='', 
model='-w', 
timezone='null', 
macAddress='null', 
jpgUrl='', 
mjpgUrl='null', 
mpegUrl='null', 
audioUrl='null', 
**## h264Url='',** 
internalHost='null', 
internalHttpPort=0, 
internalRtspPort=0, 
externalHost='', 
externalHttpPort=8080, 
externalRtspPort=0, 
cameraUsername='null', 
cameraPassword='null', 
locationLng=null, 
locationLat=null, 
isDiscoverable=null
}
we do not send **h264Url** when user specified the vendor and model in iOS and web application, only it is happening from android.

**Comment by marcoherbst** [comment]
Right, but I don't see why this is a problem.

The client can do what it likes, I would have assumed. It is down to /media ... media should only accept an h264 URL if Vendor/Model is custom.  

Or is that not obvious? 

It feels like the problem is correctly diagnosed, but is being wrongly solved. I am not confident about this, and would like your opinion.
